import { useEffect, useState } from 'react'
import { Activity, Clock3, DollarSign, AlertTriangle, CheckCircle } from 'lucide-react'
import { ragAPI } from '../lib/api.js'
import Card from '../components/ui/Card.jsx'
import Badge from '../components/ui/Badge.jsx'

function Stat({ icon: Icon, label, value, tone = 'text-accent-soft' }) { return <Card><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-lg bg-elevated flex items-center justify-center"><Icon size={17} className={tone} /></div><div><p className="text-xs text-muted">{label}</p><p className="font-display text-xl font-bold text-ink mt-0.5">{value}</p></div></div></Card> }

export default function Observability() {
  const [data, setData] = useState(null)
  const [error, setError] = useState('')
  useEffect(() => { ragAPI.observability().then(setData).catch(() => setError('Could not load observability data.')) }, [])
  if (error) return <div className="text-sm text-danger">{error}</div>
  if (!data) return <div className="flex justify-center py-20"><div className="w-8 h-8 border-2 border-accent/30 border-t-accent rounded-full animate-spin" /></div>
  return <div className="space-y-6 animate-fade-in">
    <div><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-accent/10 flex items-center justify-center"><Activity size={20} className="text-accent-soft" /></div><div><h1 className="font-display text-2xl font-bold text-ink">Observability</h1><p className="text-sm text-muted mt-1">Understand model quality, speed, cost, and reliability.</p></div></div></div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3"><Stat icon={Activity} label="Total model runs" value={data.total_runs} /><Stat icon={CheckCircle} label="Successful runs" value={data.successful_runs} tone="text-success" /><Stat icon={DollarSign} label="Estimated cost" value={`$${data.total_cost_usd}`} tone="text-warning" /><Stat icon={AlertTriangle} label="Failed runs" value={data.failed_runs} tone="text-danger" /></div>
    <div className="grid lg:grid-cols-[.8fr_1.2fr] gap-5"><Card><div className="flex items-center gap-2 mb-5"><Clock3 size={17} className="text-accent-soft" /><h2 className="font-display font-semibold text-ink">Latency percentiles</h2></div><div className="space-y-4">{[['P50', data.latency_ms.p50], ['P95', data.latency_ms.p95], ['P99', data.latency_ms.p99]].map(([label, value]) => <div key={label}><div className="flex justify-between text-xs mb-1.5"><span className="text-muted">{label}</span><span className="font-mono font-semibold text-ink">{value} ms</span></div><div className="h-2 bg-elevated rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-accent to-cyan-400 rounded-full" style={{ width: `${Math.min(100, value ? Math.max(4, (value / Math.max(data.latency_ms.p99, 1)) * 100) : 0)}%` }} /></div></div>)}</div></Card><Card><h2 className="font-display font-semibold text-ink mb-4">Model breakdown</h2>{data.models.length === 0 ? <p className="text-sm text-muted">No model runs yet.</p> : <div className="space-y-2">{data.models.map(model => <div key={model.model} className="flex items-center gap-3 rounded-xl bg-elevated/40 border border-border px-3 py-3"><div className="flex-1"><p className="text-sm font-semibold text-ink">{model.model}</p><p className="text-xs text-muted mt-1">{model.runs} runs · {model.avg_latency_ms} ms average</p></div><div className="text-right"><p className="font-mono text-sm text-accent-soft">${model.cost}</p><p className="text-[11px] text-muted">{model.failures} failures</p></div></div>)}</div>}</Card></div>
    <Card><div className="flex items-center justify-between mb-4"><h2 className="font-display font-semibold text-ink">Recent runs</h2><Badge>{data.recent_runs.length} shown</Badge></div>{data.recent_runs.length === 0 ? <p className="text-sm text-muted">Run a prompt from Experiment Lab to populate this history.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-muted border-b border-border"><tr><th className="py-2 font-medium">Model</th><th className="py-2 font-medium">Status</th><th className="py-2 font-medium">Latency</th><th className="py-2 font-medium">Tokens</th><th className="py-2 font-medium">Cost</th><th className="py-2 font-medium">Time</th></tr></thead><tbody>{data.recent_runs.map((run, index) => <tr key={`${run.created_at}-${index}`} className="border-b border-border/50"><td className="py-3 text-ink font-medium">{run.model}</td><td className="py-3"><Badge variant={run.status === 'completed' ? 'success' : 'danger'}>{run.status}</Badge></td><td className="py-3 text-muted">{run.latency_ms || 0} ms</td><td className="py-3 text-muted">{(run.input_tokens || 0) + (run.output_tokens || 0)}</td><td className="py-3 text-muted">${run.estimated_cost_usd || 0}</td><td className="py-3 text-muted">{run.created_at}</td></tr>)}</tbody></table></div>}</Card>
  </div>
}

